server:
  port: 7002

spring:
  application:
    name: eureka7002

eureka:
  instance:
    hostname: eureka7002.com # eureka服务端实例名称
  client:
    register-with-eureka: false # 是否向服务中心注册自己
    feth-registry: false # 是否向服务中心获取已有的注册信息
    service-url:
      # 设置Eureka Server 的交互地址。查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
