server:
  port: 80 # 端口

spring:
  application:
    name: irs-consumer-order # 名称

eureka: # eureka 客户端
  client:
    register-with-eureka: true # 向服务中心注册自己
    fetch-registry: true # 向服务中心获取已有的注册信息, 集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      # 服务中心链接
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

logging:
  file:
    path: ./log
  level:
    root: warn
    com.ilirus.springcloud: info
    com.ilirus.springcloud.dao: debug