server:
  port: 80 # 端口

spring:
  application:
    name: irs-consumer-order-feign # 名称

eureka: # eureka 客户端
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

# 设置超时时间
ribbon:
  # 指与服务器建立链接的超时时间(单位: ms)
  ConnectTimeout: 1000
  # 指与服务器建立链接之后，从服务器读取到可用资源所花时间
  ReadTimeout: 5000

logging:
  file:
    path: ./log
  level:
    root: warn
    com.ilirus.springcloud: info
    com.ilirus.springcloud.dao: debug
    com.ilirus.springcloud.service.PaymentFeignService: debug
