server:
  port: 80 # 端口

spring:
  application:
    name: irs-consumer-order-feign # 名称

eureka: # eureka 客户端
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

logging:
  file:
    path: ./log
  level:
    root: warn
    com.ilirus.springcloud: info
    com.ilirus.springcloud.dao: debug